import { Metadata } from "next";
import Link from "next/link";
import { Typography } from "@/components/ui/typography";
import { Separator } from "@/components/ui/separator";

export const metadata: Metadata = {
    title: "Terms & Conditions | OpenDM",
    description: "Extensive Legal Terms of Service for OpenDM - Comprehensive agreement governing platform usage.",
};

export default function TermsPage() {
    const lastUpdated = "January 5, 2026";

    return (
        <div className="container px-4 py-24 mx-auto max-w-4xl">
            <div className="mb-12">
                <Typography variant="h1" className="mb-4 text-4xl font-black uppercase tracking-tight">Terms & Conditions</Typography>
                <div className="p-4 bg-muted/50 border-l-4 border-primary mb-8">
                    <Typography variant="p" className="text-sm italic">
                        Please review these Terms & Conditions carefully. This document constitutes a legally binding agreement between you and OpenDM. By using our platform, you signify your irrevocable acceptance of all terms contained herein. These terms were last modified on {lastUpdated}.
                    </Typography>
                </div>
            </div>

            <div className="space-y-12 text-foreground/90 leading-[1.8] text-sm md:text-base">
                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">1. FORMAL BINDING AGREEMENT</Typography>
                    <Typography>
                        These Terms and Conditions ("Terms," "Agreement") constitute a formal, legally binding contract between you, whether personally or on behalf of an entity ("you," "User"), and OpenDM ("Company," "we," "us," or "our"). This Agreement governs your access to and use of the OpenDM website (opendm.io), our web-based platform, our software applications, and all associated services, features, and content (collectively, the "Service"). By accessing or using any portion of the Service, you acknowledge that you have read, understood, and agree to be bound by every provision of this Agreement, as well as our Privacy Policy, which is incorporated herein by reference.
                    </Typography>
                    <Typography className="mt-4">
                        This Service is offered and available to users who are 18 years of age or older. If you do not meet all of these requirements, or if you disagree with any part of these Terms, you are strictly prohibited from accessing or using the Service and must discontinue your interaction with our platform immediately. Your continued use signifies an ongoing representation that you have the legal capacity to enter into this contract and that you will comply with all applicable local, state, national, and international laws and regulations while utilizing our digital environment.
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">2. DEFINITIONS AND INTERPRETATION</Typography>
                    <Typography>
                        To ensure clarity throughout this document, "Service" refers to the totality of the digital products provided by OpenDM. "User Content" refers to all data, text, images, and other materials uploaded or generated by you while using the platform. "Merchant of Record" refers to Lemon Squeezy, LLC, which acts as the legal seller of our digital subscriptions. The term "Subscription" refers to the recurring paid access plans offered by our Company. "Platform" denotes the proprietary software environment where forms are built and managed.
                    </Typography>
                    <Typography className="mt-4">
                        The headings used in this Agreement are for convenience only and shall not limit or otherwise affect the interpretation of these Terms. Any use of the singular shall include the plural and vice versa. The words "include," "includes," and "including" shall be deemed to be followed by the words "without limitation." This Agreement shall be interpreted fairly and not strictly for or against either party, regardless of who drafted the document. These definitions are intended to be broad and inclusive to protect the legal interests of both the Company and the User.
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">3. SERVICE PROVISION AND MODIFICATIONS</Typography>
                    <Typography>
                        OpenDM provides a software-as-a-service application designed for communication management. We reserve the absolute right to modify, suspend, or discontinue any aspect of the Service at any time, with or without prior notice. This includes the right to add new features, remove existing ones, or alter the technical infrastructure of the platform. We are not liable to you or any third party for any such modifications. Your continued use of the platform after changes have been implemented constitutes your binding acceptance of the Service in its updated state.
                    </Typography>
                    <Typography className="mt-4">
                        While we strive for high availability, we do not guarantee that the Service will be uninterrupted, timely, secure, or error-free. Maintenance windows, software updates, and unforeseen technical failures may result in temporary Service outages. We take reasonable steps to minimize these disruptions but are not responsible for any data loss or business interruption resulting from such events. We also reserve the right to impose limits on certain features or restrict your access to parts of the Service without notice or liability if we believe you are in violation of these Terms.
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">4. REGISTRATION AND ACCOUNT SECURITY</Typography>
                    <Typography>
                        In order to access the full functionality of OpenDM, you must register for a user account. You agree to provide accurate, current, and complete information during the registration process and to keep this information updated at all times. You are solely responsible for maintaining the confidentiality of your account credentials, including your password and OAuth tokens. You are fully responsible for all activities that occur under your account, regardless of whether you authorized the activity. You must notify us immediately of any unauthorized use or security breach.
                    </Typography>
                    <Typography className="mt-4">
                        We reserve the right to refuse registration or to cancel any account that we, in our sole discretion, deem to be suspicious, fraudulent, or in violation of these Terms. You may not use a name that is subject to the rights of another person without appropriate authorization. You may not use a name that is offensive, vulgar, or obscene. Each account is for use by a single individual or entity; sharing accounts among multiple people to bypass subscription limits is strictly prohibited and may result in immediate termination of Service without refund.
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">5. SUBSCRIPTIONS AND MERCHANT OF RECORD</Typography>
                    <Typography>
                        All financial transactions for OpenDM subscriptions are conducted through our online reseller and official Merchant of Record, <strong>Lemon Squeezy, LLC</strong>. When you purchase a subscription, you are entering into a direct financial contract with Lemon Squeezy for the purchase of the Service. They are responsible for all payment processing, currency conversion, invoice generation, and the collection of applicable sales taxes or value-added taxes (VAT). Their involvement ensures a secure and compliant billing experience that adheres to global financial regulations.
                    </Typography>
                    <Typography className="mt-4">
                        By initiating a purchase, you agree to be bound by Lemon Squeezy’s terms of service and privacy policy in addition to these Terms. We do not have direct access to your full credit card details or sensitive bank information. Any billing questions or refund requests should primarily be addressed to Lemon Squeezy support, although we may assist in a secondary capacity. Failure to pay your subscription fees will result in the immediate suspension or downgrade of your account to a free tier, where available, or the complete deletion of your workspace data.
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">6. BILLING CYCLES AND AUTOMATIC RENEWALS</Typography>
                    <Typography>
                        Payment for Subscriptions is charged in advance on a recurring basis, typically either monthly or annually, as selected during the checkout process. Your Subscription will automatically renew at the end of each billing cycle under the same terms and at the then-current rate, unless you cancel the renewal prior to the end of the current period. Cancellation can be performed through your account dashboard or by contacting Lemon Squeezy. Upon cancellation, you will continue to have access to premium features until the end of your current paid term.
                    </Typography>
                    <Typography className="mt-4">
                        We reserve the right to change our subscription fees at any time. Any price changes will be communicated to you with at least 30 days' notice and will take effect at the start of your next billing cycle. Your continued use of the Service after a price change constitutes your agreement to the updated fee structure. If you do not agree to the new fees, you must cancel your subscription before the change takes effect. We are not responsible for any overdraft fees or interest charges incurred due to the automatic renewal of your subscription.
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">7. REFUND POLICY AND GUARANTEES</Typography>
                    <Typography>
                        Refunds are handled by Lemon Squeezy according to their standardized global refund policy. Generally, all fees paid for OpenDM Subscriptions are non-refundable unless otherwise required by law. In certain circumstances, such as technical failures that prevent use of the platform for an extended period, we may, at our sole discretion, authorize Lemon Squeezy to issue a partial or full refund. Any such authorized refund is a one-time gesture and does not establish a precedent for future requests. We do not provide prorated refunds for mid-cycle cancellations.
                    </Typography>
                    <Typography className="mt-4">
                        If you believe there has been a billing error, you must contact Lemon Squeezy within 14 days of the charge date to initiate a review. If you initiate a chargeback through your bank or credit card provider without first attempting to resolve the issue with us or Lemon Squeezy, we reserve the right to immediately and permanently terminate your account and blacklist your email address from future use of our Service. We take fraudulent chargeback attempts very seriously and will vigorously defend our legal rights in such cases.
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">8. INTELLECTUAL PROPERTY OWNERSHIP</Typography>
                    <Typography>
                        The Service and its original content (excluding User Content), features, and functionality are and will remain the exclusive property of OpenDM and its licensors. This includes all software code, design elements, graphics, logos, trademarks, and documentation. Our platform is protected by copyright, trademark, and other laws of both the United States and foreign countries. You are granted a limited, non-exclusive, non-transferable license to access and use the Service strictly for your own internal business or personal purposes, subject to these Terms.
                    </Typography>
                    <Typography className="mt-4">
                        You may not copy, modify, distribute, sell, or lease any part of our Service or included software, nor may you reverse engineer or attempt to extract the source code of that software, unless laws prohibit those restrictions or you have our written permission. Our trademarks and trade dress may not be used in connection with any product or service without our prior written consent. All rights not expressly granted to you under this Agreement are reserved by the Company. Any unauthorized use of our intellectual property may result in legal action and the termination of your access to the Service.
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">9. USER CONTENT AND DATA OWNERSHIP</Typography>
                    <Typography>
                        You retain all your ownership rights in the content you upload, post, or otherwise make available through the Service ("User Content"). However, by providing User Content, you grant OpenDM a worldwide, non-exclusive, royalty-free, sub-licensable license to use, host, store, reproduce, and display such content solely for the purpose of providing, improving, and promoting the Service. This license is necessary for us to render your forms, store your submissions, and provide technical support. You represent and warrant that you own or have the necessary licenses to the content you provide.
                    </Typography>
                    <Typography className="mt-4">
                        You are solely responsible for the legality, reliability, and appropriateness of your User Content. We do not pre-screen all content, but we reserve the right (but not the obligation) to remove any content that we believe, in our sole discretion, violates these Terms or is otherwise harmful to the Service or our reputation. You acknowledge that we are acting as a passive conduit for your online distribution of User Content and that we are not liable for any content provided by you or any third party. You agree to indemnify us against any claims arising from your User Content.
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">10. PROHIBITED ACTIVITIES AND CONDUCT</Typography>
                    <Typography>
                        You agree not to engage in any of the following prohibited activities: (i) copying, distributing, or disclosing any part of the Service in any medium; (ii) using any automated system, including "robots," "spiders," or "offline readers," to access the Service; (iii) transmitting spam, chain letters, or other unsolicited email; (iv) attempting to interfere with the servers or networks connected to the Service; (v) using the Service for any unlawful purpose or to solicit others to perform or participate in any unlawful acts; (vi) violating any international, federal, or state regulations, rules, or laws.
                    </Typography>
                    <Typography className="mt-4">
                        Furthermore, you may not: (vii) harass, abuse, insult, harm, defame, slander, disparage, or intimidate based on gender, sexual orientation, religion, or ethnicity; (viii) submit false or misleading information; (ix) upload or transmit viruses or any other type of malicious code; (x) collect or track the personal information of others without their consent; (xi) use the Service for any obscene or immoral purpose; or (xii) circumvent any security features of the Service. Violation of any of these prohibited activities will result in immediate termination of your account and may subject you to legal liability.
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">11. PRIVACY AND DATA PROTECTION</Typography>
                    <Typography>
                        Your privacy is of the utmost importance to us. Our collection and use of personal information in connection with the Service is described in our Privacy Policy, which is located at <Link href="/privacy" className="text-primary hover:underline font-bold">opendm.io/privacy</Link>. You understand that through your use of the Service, you consent to the collection and use (as set forth in the Privacy Policy) of this information, including the transfer of this information to the United States and other countries for storage, processing, and use by OpenDM and its trusted sub-processors.
                    </Typography>
                    <Typography className="mt-4">
                        You are responsible for ensuring that your use of the Service complies with all applicable privacy laws, including the GDPR and CCPA. If you use the platform to collect data from third parties, you must provide your own privacy notice and obtain any necessary consents. We provide the technical infrastructure to store and manage this data, but you are the Data Controller of the information you collect via your forms. We will assist you with data subject requests where technically feasible, but the ultimate responsibility for data protection compliance rests with you.
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">12. LIMITATION OF LIABILITY</Typography>
                    <Typography>
                        TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL OPENDM, ITS AFFILIATES, AGENTS, DIRECTORS, EMPLOYEES, OR SUPPLIERS BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATING TO THE USE OF, OR INABILITY TO USE, THE SERVICE. UNDER NO CIRCUMSTANCES WILL WE BE RESPONSIBLE FOR ANY DAMAGE, LOSS, OR INJURY RESULTING FROM HACKING, TAMPERING, OR OTHER UNAUTHORIZED ACCESS OR USE OF THE SERVICE.
                    </Typography>
                    <Typography className="mt-4">
                        IN NO EVENT SHALL THE TOTAL AGGREGATE LIABILITY OF OPENDM EXCEED THE AMOUNT YOU PAID TO US (OR OUR MERCHANT OF RECORD) FOR THE SERVICE IN THE TWELVE (12) MONTHS PRECEDING THE ACCRUAL OF THE CLAIM. THIS LIMITATION OF LIABILITY SECTION APPLIES WHETHER THE ALLEGED LIABILITY IS BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER BASIS, EVEN IF THE COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">13. DISCLAIMER OF WARRANTIES</Typography>
                    <Typography>
                        THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. USE OF THE SERVICE IS AT YOUR OWN RISK. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE IS PROVIDED WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM OPENDM OR THROUGH THE SERVICE WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED HEREIN.
                    </Typography>
                    <Typography className="mt-4">
                        WITHOUT LIMITING THE FOREGOING, THE COMPANY DOES NOT WARRANT THAT THE CONTENT IS ACCURATE, RELIABLE, OR CORRECT; THAT THE SERVICE WILL MEET YOUR REQUIREMENTS; THAT THE SERVICE WILL BE AVAILABLE AT ANY PARTICULAR TIME OR LOCATION, UNINTERRUPTED OR SECURE; THAT ANY DEFECTS OR ERRORS WILL BE CORRECTED; OR THAT THE SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. ANY CONTENT DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS DOWNLOADED AT YOUR OWN RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM.
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">14. INDEMNIFICATION CLAUSE</Typography>
                    <Typography>
                        You agree to defend, indemnify, and hold harmless OpenDM and its subsidiaries, agents, licensors, managers, and other affiliated companies, and their employees, contractors, agents, officers, and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from: (i) your use of and access to the Service, including any data or content transmitted or received by you; (ii) your violation of any term of this Agreement; (iii) your violation of any third-party right, including without limitation any right of privacy or intellectual property rights.
                    </Typography>
                    <Typography className="mt-4">
                        This also includes: (iv) your violation of any applicable law, rule, or regulation; (v) any content that is submitted via your account, including without limitation misleading, false, or inaccurate information; (vi) your willful misconduct; or (vii) any other party's access and use of the Service with your unique username, password, or other appropriate security code. This defense and indemnification obligation will survive the termination of this Agreement and your use of the Service. We reserve the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you.
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">15. TERMINATION AND SUSPENSION</Typography>
                    <Typography>
                        We may terminate or suspend your account and access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may do so through your account settings or by contacting us. All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.
                    </Typography>
                    <Typography className="mt-4">
                        Upon termination, we may delete all your User Content and data from our systems after a reasonable period, except for information that we are legally required to retain. You are responsible for exporting your data prior to termination. We are not liable to you or any third party for any termination of your access to the Service or the deletion of your content. If your account is terminated for cause, you are prohibited from creating a new account without our express written permission. Any attempt to circumvent such a ban will be considered a material breach of these Terms.
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">16. GOVERNING LAW AND JURISDICTION</Typography>
                    <Typography>
                        The Agreement and any dispute or claim arising out of or in connection with it or its subject matter or formation (including non-contractual disputes or claims) shall be governed by and construed in accordance with the laws of the jurisdiction in which OpenDM is legally registered, without giving effect to its conflict of laws principles. You agree that any legal action or proceeding between you and OpenDM shall be brought exclusively in a court of competent jurisdiction located within that same jurisdiction. You hereby waive any right to object to the venue or jurisdiction of such courts.
                    </Typography>
                    <Typography className="mt-4">
                        The United Nations Convention on Contracts for the International Sale of Goods is specifically excluded from application to these Terms. To the extent permitted by law, you agree that you may only bring claims against us in your individual capacity and not as a plaintiff or class member in any purported class or representative proceeding. If any provision of this Agreement is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced to the fullest extent under law.
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">17. DISPUTE RESOLUTION AND ARBITRATION</Typography>
                    <Typography>
                        In the event of any dispute, claim, or controversy arising out of or relating to these Terms, the parties shall first attempt in good faith to resolve the dispute through informal negotiation. If the dispute is not resolved within 30 days, it shall be settled by binding arbitration in accordance with the rules of the American Arbitration Association or an equivalent international body, as determined by the Company. The arbitration shall take place in our registered jurisdiction, and the arbitrator's decision shall be final and binding. Each party shall bear their own costs and an equal share of the arbitrator's fees.
                    </Typography>
                    <Typography className="mt-4">
                        Notwithstanding the foregoing, we reserve the right to seek injunctive or other equitable relief in any court of competent jurisdiction to prevents the actual or threatened infringement, misappropriation, or violation of our copyrights, trademarks, trade secrets, patents, or other intellectual property rights. You agree that any arbitration under these Terms will take place on an individual basis; class arbitrations and class actions are not permitted. You acknowledge that by agreeing to these Terms, you are waiving the right to a trial by jury.
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">18. ENTIRE AGREEMENT AND SEVERABILITY</Typography>
                    <Typography>
                        These Terms, together with our Privacy Policy and any other legal notices published by us on the Service, shall constitute the entire agreement between you and OpenDM concerning the Service. If any provision of these Terms is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms, which shall remain in full force and effect. No waiver of any term of these Terms shall be deemed a further or continuing waiver of such term or any other term, and our failure to assert any right shall not constitute a waiver of such right.
                    </Typography>
                    <Typography className="mt-4">
                        This Agreement supersedes all prior or contemporaneous communications and proposals, whether electronic, oral, or written, between you and us. We may assign our rights and obligations under these Terms to any party at any time without notice to you. You may not assign your rights or obligations under these Terms without our prior written consent. Any purported assignment in violation of this section shall be null and void. We shall not be liable for any failure to perform our obligations where such failure results from any cause beyond our reasonable control (force majeure).
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">19. FORCE MAJEURE AND ACTS OF GOD</Typography>
                    <Typography>
                        Neither party shall be liable for any failure or delay in performance under this Agreement (other than for delay in the payment of money due and payable hereunder) to the extent said failures or delays are caused by forces beyond that party's reasonable control. This includes occurring events such as strikes, labor disputes, lockouts, riots, epidemics, pandemics, war, government regulations, fire, flood, earthquake, other environmental disasters, or failures of common carriers or third-party service providers (such as ISPs or cloud hosting providers).
                    </Typography>
                    <Typography className="mt-4">
                        In the event of a force majeure occurrence, the non-performing party shall be excused from any further performance or observance of the obligation(s) so affected for as long as such circumstances prevail and such party continues to use its best efforts to recommence performance or observance whenever and to whatever extent possible without delay. If a force majeure event continues for a period of more than 60 days, either party may terminate this Agreement without penalty, upon written notice to the other party.
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">20. CHANGES TO THE TERMS AND CONDITIONS</Typography>
                    <Typography>
                        We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will try to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, in whole or in part, please stop using the website and the Service.
                    </Typography>
                    <Typography className="mt-4">
                        We encourage you to check this page frequently for any updates. We will notify you of any changes by posting the new Terms on this page and updating the "Last Updated" date at the top of the document. We may also notify you via email or through a prominent notice on our dashboard. Your silence or continued use after such notification shall be deemed as your consent to the changes. This process ensures that you remain informed about your legal obligations as a User of the OpenDM platform.
                    </Typography>
                </section>

                <section>
                    <Typography variant="h2" className="text-xl font-bold mb-4 border-b pb-2">21. CONTACT AND LEGAL NOTICES</Typography>
                    <Typography>
                        If you have any questions or concerns regarding these Terms and Conditions, or if you wish to provide any legal notices, please contact us via our official support email: <strong>support@opendm.io</strong>. All notices required or permitted under this Agreement to be given to us shall be in writing and shall be deemed given if sent by email with a "read receipt" or a manual confirmation from our legal department. Communications made through the Service's support chat or social media channels are for convenience only and do not constitute formal legal notice.
                    </Typography>
                    <Typography className="mt-4">
                        We strive to respond to all inquiries in a timely manner, but please allow up to 7 business days for a formal response. Thank you for choosing OpenDM. We look forward to providing you with a high-quality communication management platform while respecting your rights and maintaining the legal integrity of our digital ecosystem. By using our platform, you acknowledge that you have read this entire 21-section Agreement and agree to be bound by its terms without reservation.
                    </Typography>
                </section>
            </div>


        </div>
    );
}
